version: '3'

services:
  web:
    env_file: .env   # Change env_sample.txt to env.txt
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/code
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    ports:
      - 8080:8000
    # entrypoint: sh /code/entrypoint.sh

  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    # ports:
    #   - 5432:5432
    env_file:
      - .env


  redis:
    image: redis:alpine
    restart: always
    entrypoint: redis-server --appendonly yes
    # ports:
    #   - 6379:6379
    volumes:
      - ./redis_data:/var/lib/redis
      - ./redis/rc.local:/etc/rc.local

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    entrypoint: "celery --app loyalbites worker -f /logs/worker.log --loglevel=info"
    depends_on:
      - web
      - redis
    volumes:
      - .:/code
      - ./logs/:/logs/
    env_file:
      - .env


  beat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    entrypoint: "celery --app loyalbites beat -f /logs/worker.log --loglevel=info"
    depends_on:
      - web
      - redis
    volumes:
      - .:/code
      - ./logs/:/logs/
    env_file:
      - .env